from typing import List, Dict, Any, Optional, Union

from davinci_resolve import MediaPoolItem, TimelineItem, Timeline


class MediaPool:
    def GetRootFolder(self) -> "Folder": ...
    def AddSubFolder(self, folder: "Folder", name: str) -> "Folder": ...
    def RefreshFolders(self) -> bool: ...
    def CreateEmptyTimeline(self, name: str) -> "Timeline": ...

    def AppendToTimeline(self, *clips: "MediaPoolItem") -> List["TimelineItem"]: ...
    def AppendToTimeline(self, clips: List["MediaPoolItem"]) -> List["TimelineItem"]: ...
    def AppendToTimeline(self, clipInfo: List[Dict[str, Any]]) -> List["TimelineItem"]: ...

    def CreateTimelineFromClips(self, name: str, *clips: "MediaPoolItem") -> "Timeline": ...
    def CreateTimelineFromClips(self, name: str, clips: List["MediaPoolItem"]) -> "Timeline": ...
    def CreateTimelineFromClips(self, name: str, clipInfo: List[Dict[str, Any]]) -> "Timeline": ...

    def ImportTimelineFromFile(
        self,
        filePath: str,
        importOptions: Optional[Dict[str, Any]] = None
    ) -> "Timeline": ...

    def DeleteTimelines(self, timelines: List["Timeline"]) -> bool: ...
    def GetCurrentFolder(self) -> "Folder": ...
    def SetCurrentFolder(self, folder: "Folder") -> bool: ...

    def DeleteClips(self, clips: List["MediaPoolItem"]) -> bool: ...

    def ImportFolderFromFile(
        self,
        filePath: str,
        sourceClipsPath: str = ""
    ) -> bool: ...

    def DeleteFolders(self, subfolders: List["Folder"]) -> bool: ...
    def MoveClips(self, clips: List["MediaPoolItem"], targetFolder: "Folder") -> bool: ...
    def MoveFolders(self, folders: List["Folder"], targetFolder: "Folder") -> bool: ...

    def GetClipMatteList(self, item: "MediaPoolItem") -> List[str]: ...
    def GetTimelineMatteList(self, folder: "Folder") -> List["MediaPoolItem"]: ...
    def DeleteClipMattes(self, item: "MediaPoolItem", paths: List[str]) -> bool: ...

    def RelinkClips(self, items: List["MediaPoolItem"], folderPath: str) -> bool: ...
    def UnlinkClips(self, items: List["MediaPoolItem"]) -> bool: ...

    def ImportMedia(self, items: List[str]) -> List["MediaPoolItem"]: ...
    def ImportMedia(self, clipInfo: List[Dict[str, Any]]) -> List["MediaPoolItem"]: ...

    def ExportMetadata(
        self,
        fileName: str,
        clips: Optional[List["MediaPoolItem"]] = None
    ) -> bool: ...

    def GetUniqueId(self) -> str: ...

    def CreateStereoClip(
        self,
        left: "MediaPoolItem",
        right: "MediaPoolItem"
    ) -> "MediaPoolItem": ...

    def AutoSyncAudio(
        self,
        items: List["MediaPoolItem"],
        audioSyncSettings: Optional[Dict[str, Any]] = None
    ) -> bool: ...

    def GetSelectedClips(self) -> List["MediaPoolItem"]: ...
    def SetSelectedClip(self, item: "MediaPoolItem") -> bool: ...


class Folder:
    def GetClipList(self) -> List["MediaPoolItem"]: ...
    def GetName(self) -> str: ...
    def GetSubFolderList(self) -> List["Folder"]: ...
    def GetIsFolderStale(self) -> bool: ...
    def GetUniqueId(self) -> str: ...
    def Export(self, filePath: str) -> bool: ...
    def TranscribeAudio(self) -> bool: ...
    def ClearTranscription(self) -> bool: ...

