class ProjectManager:
    def ArchiveProject(*args, **kwargs): ...
    def CloseProject(self, project: Any) -> bool: ...
    def CreateCloudProject(self, {cloudSettings}: Any) -> Any: ...
    def CreateFolder(self, folderName: Any) -> bool: ...
    def CreateProject(self, projectName: Any, mediaLocationPath: Any) -> Any: ...
    def DeleteFolder(self, folderName: Any) -> bool: ...
    def DeleteProject(self, projectName: Any) -> bool: ...
    def ExportProject(self, projectName: Any, filePath: Any, withStillsAndLUTs=True: Any) -> bool: ...
    def GetCurrentDatabase(*args, **kwargs): ...
    def GetCurrentFolder(self) -> Any: ...
    def GetCurrentProject(self) -> Any: ...
    def GetDatabaseList(*args, **kwargs): ...
    def GetFolderListInCurrentFolder(*args, **kwargs): ...
    def GetFoldersInCurrentFolder(*args, **kwargs): ...
    def GetProjectLastModifiedTime(*args, **kwargs): ...
    def GetProjectListInCurrentFolder(*args, **kwargs): ...
    def GetProjectsInCurrentFolder(*args, **kwargs): ...
    def GotoParentFolder(self) -> bool: ...
    def GotoRootFolder(self) -> bool: ...
    def ImportCloudProject(self, filePath: Any, {cloudSettings}: Any) -> bool: ...
    def ImportProject(self, filePath: Any, projectName=None: Any) -> bool: ...
    def LoadCloudProject(self, {cloudSettings}: Any) -> Any: ...
    def LoadProject(self, projectName: Any) -> Any: ...
    def OpenFolder(self, folderName: Any) -> bool: ...
    def Print(*args, **kwargs): ...
    def RestoreCloudProject(self, folderPath: Any, {cloudSettings}: Any) -> bool: ...
    def RestoreProject(self, filePath: Any, projectName=None: Any) -> bool: ...
    def SaveProject(self) -> bool: ...
    def SetCurrentDatabase(self, {dbInfo}: Any) -> bool: ...
