class Project:
    def AddColorGroup(self, groupName: Any) -> Any: ...
    def AddRenderJob(self) -> Any: ...
    def ApplyFairlightPresetToCurrentTimeline(self, name: Any) -> bool: ...
    def DeleteAllRenderJobs(self) -> bool: ...
    def DeleteColorGroup(self, colorGroup: Any) -> bool: ...
    def DeleteRenderJob(self, jobId: Any) -> bool: ...
    def DeleteRenderPreset(self, presetName: Any) -> bool: ...
    def ExportCurrentFrameAsStill(self, filePath: Any) -> bool: ...
    def GetColorGroupsList(*args, **kwargs): ...
    def GetCurrentRenderFormatAndCodec(*args, **kwargs): ...
    def GetCurrentRenderMode(self) -> Any: ...
    def GetCurrentTimeline(self) -> Any: ...
    def GetGallery(self) -> Any: ...
    def GetMediaPool(self) -> Any: ...
    def GetName(self) -> str: ...
    def GetPresetList(*args, **kwargs): ...
    def GetPresets(*args, **kwargs): ...
    def GetQuickExportRenderPresets(*args, **kwargs): ...
    def GetRenderCodecs(*args, **kwargs): ...
    def GetRenderFormats(*args, **kwargs): ...
    def GetRenderJobList(*args, **kwargs): ...
    def GetRenderJobStatus(*args, **kwargs): ...
    def GetRenderJobs(*args, **kwargs): ...
    def GetRenderPresetList(*args, **kwargs): ...
    def GetRenderPresets(*args, **kwargs): ...
    def GetRenderResolutions(*args, **kwargs): ...
    def GetSetting(self, settingName: Any) -> Any: ...
    def GetTimelineByIndex(self, idx: Any) -> Any: ...
    def GetTimelineCount(self) -> Any: ...
    def GetUniqueId(self) -> Any: ...
    def InsertAudioToCurrentTrackAtPlayhead(*args, **kwargs): ...
    def IsRenderingInProgress(self) -> bool: ...
    def LoadBurnInPreset(self, presetName: Any) -> bool: ...
    def LoadRenderPreset(self, presetName: Any) -> bool: ...
    def Print(*args, **kwargs): ...
    def RefreshLUTList(self) -> bool: ...
    def RenderWithQuickExport(*args, **kwargs): ...
    def SaveAsNewRenderPreset(self, presetName: Any) -> bool: ...
    def SetCurrentRenderFormatAndCodec(self, format: Any, codec: Any) -> bool: ...
    def SetCurrentRenderMode(self, renderMode: Any) -> bool: ...
    def SetCurrentTimeline(self, timeline: Any) -> bool: ...
    def SetName(self, groupName: Any) -> bool: ...
    def SetPreset(self, presetName: Any) -> bool: ...
    def SetRenderSettings(self, {settings}: Any) -> bool: ...
    def SetSetting(self, settingName: Any, settingValue: Any) -> bool: ...
    def StartRendering(self, [idxs...]: Any) -> bool: ...
    def StopRendering(self) -> None: ...
