class Resolve:
    def DeleteLayoutPreset(self, presetName: Any) -> bool: ...
    def ExportBurnInPreset(self, presetName: Any, exportPath: Any) -> bool: ...
    def ExportLayoutPreset(self, presetName: Any, presetFilePath: Any) -> bool: ...
    def ExportRenderPreset(self, presetName: Any, exportPath: Any) -> bool: ...
    def Fusion(self) -> Any: ...
    def GetCurrentPage(self) -> str: ...
    def GetFairlightPresets(*args, **kwargs): ...
    def GetKeyframeMode(self) -> Any: ...
    def GetMediaStorage(self) -> Any: ...
    def GetProductName(self) -> Any: ...
    def GetProjectManager(self) -> Any: ...
    def GetVersion(*args, **kwargs): ...
    def GetVersionString(self) -> Any: ...
    def ImportBurnInPreset(self, presetPath: Any) -> bool: ...
    def ImportLayoutPreset(self, presetFilePath: Any, presetName: Any) -> bool: ...
    def ImportRenderPreset(self, presetPath: Any) -> bool: ...
    def LoadLayoutPreset(self, presetName: Any) -> bool: ...
    def OpenPage(self, pageName: Any) -> bool: ...
    def Print(*args, **kwargs): ...
    def Quit(self) -> None: ...
    def SaveLayoutPreset(self, presetName: Any) -> bool: ...
    def SetHighPriority(*args, **kwargs): ...
    def SetKeyframeMode(self, keyframeMode: Any) -> bool: ...
    def UpdateLayoutPreset(self, presetName: Any) -> bool: ...
