from davinci_resolve import MediaPoolItem


class TimelineItem:
    def GetName(self) -> str: ...
    def SetName(self, name: Any) -> bool: ...
    def GetDuration(self, subframe_precision: bool = False) -> Union[int, float]: ...
    def GetEnd(self, subframe_precision: bool = False) -> Union[int, float]: ...
    def GetSourceEndFrame(self) -> int: ...
    def GetSourceEndTime(self) -> float: ...
    def GetFusionCompCount(self) -> int: ...
    def GetFusionCompByIndex(self, compIndex: Any) -> Any: ...
    def GetFusionCompNameList(self) -> List[str]: ...
    def GetFusionCompByName(self, compName: Any) -> Any: ...
    def GetLeftOffset(self, subframe_precision: Any) -> Union[int, float]: ...
    def GetRightOffset(self, subframe_precision: Any) -> Union[int, float]: ...
    def GetStart(self, subframe_precision: bool = False) -> Union[int, float]: ...
    def GetSourceStartFrame(self) -> int: ...
    def GetSourceStartTime(self) -> float: ...
    def SetProperty(self, propertyKey: Any, propertyValue: Any) -> bool: ...
    def GetProperty(self, propertyKey: Any) -> Any: ...
    def GetMarkers(self) -> Dict: ...
    def GetMarkerByCustomData(self, customData: Any) -> Dict: ...
    def UpdateMarkerCustomData(self, frameId: Any, customData: Any) -> bool: ...
    def GetMarkerCustomData(self, frameId: Any) -> str: ...
    def DeleteMarkersByColor(self, color: Any) -> bool: ...
    def DeleteMarkerAtFrame(self, frameNum: Any) -> bool: ...
    def DeleteMarkerByCustomData(self, customData: Any) -> bool: ...
    def AddFlag(self, color: Any) -> bool: ...
    def GetFlagList(self) -> List[str]: ...
    def ClearFlags(self, color: Any) -> bool: ...
    def GetClipColor(self) -> str: ...
    def SetClipColor(self, colorName: Any) -> bool: ...
    def ClearClipColor(self) -> bool: ...
    def AddFusionComp(self) -> Any: ...
    def ImportFusionComp(self, path: Any) -> Any: ...
    def ExportFusionComp(self, path: Any, compIndex: Any) -> bool: ...
    def DeleteFusionCompByName(self, compName: Any) -> bool: ...
    def LoadFusionCompByName(self, compName: Any) -> Any: ...
    def RenameFusionCompByName(self, oldName: Any, newName: Any) -> bool: ...
    def AddVersion(self, versionName: Any, versionType: Any) -> bool: ...
    def GetCurrentVersion(self) -> Dict: ...
    def DeleteVersionByName(self, versionName: Any, versionType: Any) -> bool: ...
    def LoadVersionByName(self, versionName: Any, versionType: Any) -> bool: ...
    def RenameVersionByName(self, oldName: Any, newName: Any, versionType: Any) -> bool: ...
    def GetVersionNameList(self, versionType: Any) -> List[str]: ...
    def GetMediaPoolItem(self) -> "MediaPoolItem": ...
    def GetStereoConvergenceValues(self) -> Dict: ...
    def GetStereoLeftFloatingWindowParams(self) -> Dict: ...
    def GetStereoRightFloatingWindowParams(self) -> Dict: ...
    def SetCDL(self, [CDL map]: Any) -> bool: ...
    def AddTake(self, mediaPoolItem: Any, startFrame: Any, endFrame: Any) -> bool: ...
    def GetSelectedTakeIndex(self) -> int: ...
    def GetTakesCount(self) -> int: ...
    def GetTakeByIndex(self, idx: Any) -> Dict: ...
    def DeleteTakeByIndex(self, idx: Any) -> bool: ...
    def SelectTakeByIndex(self, idx: Any) -> bool: ...
    def FinalizeTake(self) -> bool: ...
    def CopyGrades(self, [tgtTimelineItems]: Any) -> bool: ...
    def SetClipEnabled(self, Bool: Any) -> bool: ...
    def GetClipEnabled(self) -> bool: ...
    def UpdateSidecar(self) -> bool: ...
    def GetUniqueId(self) -> str: ...
    def LoadBurnInPreset(self, presetName: Any) -> bool: ...
    def CreateMagicMask(self, mode: Any) -> bool: ...
    def RegenerateMagicMask(self) -> bool: ...
    def Stabilize(self) -> bool: ...
    def SmartReframe(self) -> bool: ...
    def GetNodeGraph(self, layerIdx: Any) -> Any: ...
    def GetColorGroup(self) -> Any: ...
    def AssignToColorGroup(self, ColorGroup: Any) -> bool: ...
    def RemoveFromColorGroup(self) -> bool: ...
    def ExportLUT(self, exportType: Any, path: Any) -> bool: ...
    def GetLinkedItems(self) -> List[Any]: ...
    def GetTrackTypeAndIndex(self) -> List[Any]: ...
    def GetSourceAudioChannelMapping(self) -> Any: ...
    def GetIsColorOutputCacheEnabled(self) -> Any: ...
    def GetIsFusionOutputCacheEnabled(self) -> Any: ...
    def SetColorOutputCache(self, cache_value: Any) -> bool: ...
    def SetFusionOutputCache(self, cache_value: Any) -> bool: ...
    def GetVoiceIsolationState(self) -> Dict: ...
    def SetVoiceIsolationState(self, {VoiceIsolationState}: Any) -> bool: ...
    def ResetAllNodeColors(self) -> bool: ...
