from typing import Dict
from xxlimited import Str


class Timeline:
    def AddMarker(self,frameId, color, name, note, duration, customData = None) -> bool         : ...      # Creates a new marker at given frameId position and with given marker information. 'customData' is optional and helps to attach user specific data to the marker.
    def AddTrack(self, trackType: Any, newTrackOptions: Any) -> bool: ...
    def AnalyzeDolbyVision(*args, **kwargs): ...
    def ClearMarkInOut(self, type="all": Any) -> bool: ...
    def ConvertTimelineToStereo(self) -> bool: ...
    def CreateCompoundClip(self, timelineItems: list["TimelineItem"], clipInfo: Dict[str,str]) -> Any: ...
    def CreateFusionClip(self, [timelineItems]: Any) -> Any: ...
    def CreateSubtitlesFromAudio(self, {autoCaptionSettings}: Any) -> bool: ...
    def DeleteClips(self, [timelineItems]: Any, Bool: Any) -> bool: ...
    def DeleteMarkerAtFrame(self, frameNum: Any) -> bool: ...
    def DeleteMarkerByCustomData(self, customData: Any) -> bool: ...
    def DeleteMarkersByColor(self, color: Any) -> bool: ...
    def DeleteTrack(self, trackType: Any, trackIndex: Any) -> bool: ...
    def DetectSceneCuts(self) -> bool: ...
    def DuplicateTimeline(self, timelineName: Any) -> "Timeline": ...
    def Export(self, fileName: Any, exportType: Any, exportSubtype: Any) -> bool: ...
    def GetCurrentClipThumbnailImage(*args, **kwargs): ...
    def GetCurrentTimecode(self) -> Any: ...
    def GetCurrentVideoItem(self) -> Any: ...
    def GetEndFrame(self) -> Any: ...
    def GetIsTrackEnabled(self, trackType: Any, trackIndex: Any) -> bool: ...
    def GetIsTrackLocked(self, trackType: Any, trackIndex: Any) -> bool: ...
    def GetItemListInTrack(self, trackType: Any, trackIndex: Any): ...
    def GetItemsInTrack(self, trackType: Any, trackIndex: Any): ...
    def GetMarkInOut(*args, **kwargs): ...
    def GetMarkerByCustomData(*args, **kwargs): ...
    def GetMarkerCustomData(self, frameId: Any) -> Any: ...
    def GetMarkers(*args, **kwargs): ...
    def GetMediaPoolItem(self) -> Any: ...
    def GetName(self) -> str: ...
    def GetNodeGraph(self, layerIdx: Any) -> Any: ...
    def GetSetting(self, settingName: Any) -> Any: ...
    def GetStartFrame(self) -> Any: ...
    def GetStartTimecode(self) -> Any: ...
    def GetTrackCount(self, trackType: Any) -> Any: ...
    def GetTrackName(self, trackType: Any, trackIndex: Any) -> Any: ...
    def GetTrackSubType(self, trackType: Any, trackIndex: Any) -> Any: ...
    def GetUniqueId(self) -> Any: ...
    def GetVoiceIsolationState(*args, **kwargs): ...
    def GrabAllStills(*args, **kwargs): ...
    def GrabStill(self) -> Any: ...
    def ImportIntoTimeline(self, filePath: Any, {importOptions}: Any) -> bool: ...
    def InsertFusionCompositionIntoTimeline(self) -> Any: ...
    def InsertFusionGeneratorIntoTimeline(self, generatorName: Any) -> Any: ...
    def InsertFusionTitleIntoTimeline(self, titleName: Any) -> Any: ...
    def InsertGeneratorIntoTimeline(self, generatorName: Any) -> Any: ...
    def InsertOFXGeneratorIntoTimeline(self, generatorName: Any) -> Any: ...
    def InsertTitleIntoTimeline(self, titleName: Any) -> Any: ...
    def Print(*args, **kwargs): ...
    def SetClipsLinked(self, [timelineItems]: Any, Bool: Any) -> bool: ...
    def SetCurrentTimecode(self, timecode: Any) -> bool: ...
    def SetMarkInOut(self, in: Any, out: Any, type="all": Any) -> bool: ...
    def SetName(self, groupName: Any) -> bool: ...
    def SetSetting(self, settingName: Any, settingValue: Any) -> bool: ...
    def SetStartTimecode(self, timecode: Any) -> bool: ...
    def SetTrackEnable(self, trackType: Any, trackIndex: Any, Bool: Any) -> bool: ...
    def SetTrackLock(self, trackType: Any, trackIndex: Any, Bool: Any) -> bool: ...
    def SetTrackName(self, trackType: Any, trackIndex: Any, name: Any) -> bool: ...
    def SetVoiceIsolationState(self, {VoiceIsolationState}: Any) -> bool: ...
    def UpdateMarkerCustomData(self, frameId: Any, customData: Any) -> bool: ...
